# This is a basic workflow to help you get started with Actions

name: EODMS-CLI Test 1 - Process 1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "development" branch
  # push:
  #   branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'development'
          
      # - name: Use local workflows/files
      #   uses: ./.github/workflows/files
      
      # List files
      - name: List files
        run: ls
      
      # Install requirements
      - name: Install requirements
        run: pip install -r requirements.txt

      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 1 - Process 1
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        # run: python eodms_cli.py -u $USERNAME -p $PASSWORD -c RCMImageProducts,Radarsat2 -d 20190101-20220527 -i tests/files/NCR_AOI.geojson -max 2:1 -prc full -ov 30 -f "RCMImageProducts.beam_mnemonic like 16M%%,RCMImageProducts.product_type=SLC,Radarsat2.beam_mnemonic like EH%%,Radarsat2.transmit_polarization=H" -o tests/files/test1_output.geojson -pri low -s
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_process1
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 2 - Process 2
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_process2
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 3 - Process 3
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_process3
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 4 - Process 4
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_process4
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 5 - Process 5
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_process5
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 6 - Process 1 Search Only
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_searchonly
          
      # Runs a single command using the runners shell
      - name: Run EODMS-CLI Prompt Test 7 - Wrong Creds
        continue-on-error: true
        env:
          EODMS_USER: ${{ secrets.EODMS_USER }}
          EODMS_PASSWORD: ${{ secrets.EODMS_PWD }}
        run: |
          cd test
          python -m unittest test_prompt.TestEodmsCli.test_wrongcreds
        
      # List files
      - name: List files
        run: ls

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
